\c acroyoga

INSERT INTO poses (name,type,difficulty,number_of_people,img) VALUES
('Headfirst Grasshopper','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2017/04/DSC_3603-2.jpg'),
('Hanging Bat','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/2016-09-20-11.38.58-1.jpg'),
('Moon Bridge','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2017/01/3.jpg'),
('Ostrich Lab','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/12/7fm90e3UCS4.jpeg'),
('Foot-To-Foot Lord of the Dance Pose','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Foot-to-foot-Lord-of-the-dance-pose-.jpg'),
('Lotus Pile','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2017/04/Lotus-Pile.jpg'),
('Bowsprit','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/07/DSC_6511.jpg'),
('Double Throne','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2016/09/double-throne.jpg'),
('Sticky Lab','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/12/iClGiKBN_4.jpeg'),
('Birds Dive','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/12/2016-04-13_11-59-47.jpg'),
('Reverse Space Needle','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/08/Supine-Super-Free-Reverse-Star.jpg'),
('Goofy Goofy Foot to Foot','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2017/01/Goofy-Goofy-Foot-to-Foot.jpg'),
('Reverse Foot-To-Foot','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/IMG_1020_mini.jpg'),
('Foot Sirsasana','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/12/Foot-Sirasana.jpg'),
('Asymmetrical on Foot','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Assym.jpg'),
('Reverse Low Foot-To-Hand','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Low-Reverse-Foot-to-Hand.jpg'),
('Calatrava','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2017/03/Calatrava.jpg'),
('Thinker','L-Base','Easy','2 Person','https://www.acropedia.org/wp-content/uploads/2016/10/Thinker.jpg'),
('Vishnu’s Hook','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Vishnus-Hook-1.jpg'),
('Satellite','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/IMG_8277.jpg'),
('Foot-To-Foot Headstand','L-Base','Really Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Foot-to-Foot-Headstand.jpg'),
('Bluejay','L-Base','Hard','4 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Bluejay.jpg'),
('Pike Pyramid','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2016/07/DSC_3541.jpg'),
('Bicep Stand','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/08/Bicep-Stand-Supine.jpg'),
('Maple','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2017/07/maple-lesh-amir.jpg'),
('Goofy Chair','L-Base','Easy','2 Person','https://www.acropedia.org/wp-content/uploads/2017/04/goofy-chair-1.jpg'),
('Scorpions Kiss','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2017/04/scorpion-side.jpg'),
('Boredstand','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Boredstand.jpg');