\c acroyoga
INSERT INTO poses (name,type,difficulty,number_of_people,img) VALUES
('Moon Bridge','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2017/01/3.jpg'),
('Double Throne','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2016/09/double-throne.jpg'),
('Side Back Bird','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2015/11/DSC_9172.jpg'),
('Double Couch','L-Base','Hard','3 Person','http://i2.wp.com/www.acropedia.org/wp-content/uploads/2016/03/12646787_10156468909990224_5418672029104218775_o.jpg?fit=1080%2C1080&ssl=1'),
('Tree Pose on Shin','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/05/Tree-Pose-on-Shin.jpg'),
('Levered Hand to Hand Trio','L-Base','Really Hard','3 Person','https://www.acropedia.org/wp-content/uploads/2016/05/Levered-Hand-to-Hand-Trio.jpg'),
('The Archer','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2016/06/The-Archer.jpeg'),
('Star','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2013/02/Kadri-Kurgun-Star-3.jpg'),
('The Buddha','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/05/The-Buddha.jpg'),
('Teeter Totter','L-Base','Really Hard','3 Person','https://www.acropedia.org/wp-content/uploads/2016/06/Teeter-Totter.jpg'),
('Mono Foot to Foot','L-Base','Really Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/07/Толик.jpg'),
('Low Reverse Hand to Hand','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/08/Supine-Low-Reverse-Hand-to-Hand.jpg'),
('Reverse Needle','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/08/Reverse-Needle.jpg'),
('Bowsprit','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/07/DSC_6511.jpg'),
('Foot-To-Foot Headstand','L-Base','Really Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Foot-to-Foot-Headstand.jpg'),
('Goofy Goofy Foot to Foot','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2017/01/Goofy-Goofy-Foot-to-Foot.jpg'),
('Vishnu’s Hook','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Vishnus-Hook-1.jpg'),
('Bicep Stand','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/08/Bicep-Stand-Supine.jpg'),
('Reverse Space Needle','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/08/Supine-Super-Free-Reverse-Star.jpg'),
('Heart to Knees','L-Base','Easy','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Knees-to-Heart.jpg?fit=600%2C400&ssl=1'),
('Baby Hand to Hand','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/08/Baby-Hand-to-Hand.jpg'),
('Back Bow','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Backbow.jpg?fit=600%2C400&ssl=1'),
('Satellite','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/IMG_8277.jpg'),
('Back Plank','L-Base','Easy','2 Person','https://i2.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Back-Plank2.jpg?fit=600%2C400&ssl=1'),
('Reverse Vishnu’s Couch','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Reverse-Vishnus-Couch-Tag.jpg?fit=600%2C400&ssl=1'),
('Care Bear Stare','L-Base','Easy','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2014/01/Care-Bear-Stare.jpg?fit=600%2C400&ssl=1'),
('Bird','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2015/11/DSC_6759.jpg?fit=1920%2C1500&ssl=1'),
('Needle','L-Base','Expert','2 Person','https://i2.wp.com/www.acropedia.org/wp-content/uploads/2015/09/Super-Free-Shoulder-Stand1.jpg?fit=600%2C400&ssl=1'),
('Thinker','L-Base','Easy','2 Person','https://www.acropedia.org/wp-content/uploads/2016/10/Thinker.jpg'),
('Lotus Pile','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2017/04/Lotus-Pile.jpg'),
('Reverse Low Foot-To-Hand','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Low-Reverse-Foot-to-Hand.jpg'),
('Reverse Foot-To-Foot','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/IMG_1020_mini.jpg'),
('Asymmetrical on Foot','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Assym.jpg'),
('Goofy Chair','L-Base','Easy','2 Person','https://www.acropedia.org/wp-content/uploads/2017/04/goofy-chair-1.jpg'),
('Calatrava','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2017/03/Calatrava.jpg'),
('Scorpions Kiss','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2017/04/scorpion-side.jpg'),
('Sticky Lab','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/12/iClGiKBN_4.jpeg'),
('Ostrich Lab','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/12/7fm90e3UCS4.jpeg'),
('Leaf Stretch','L-Base','Easy','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Leaf-Stretch.jpg'),
('Chest stand','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/03/Chest-Stand.jpg'),
('High Foot-to-Hand','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/01/DSC_6820.jpg'),
('Hanging Bat','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/2016-09-20-11.38.58-1.jpg'),
('Bird on Hands','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/01/DSC_6764.jpg'),
('Birds Dive','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/12/2016-04-13_11-59-47.jpg'),
('Dragonfly','L-Base','Really Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/04/girl-dragonfly.jpg'),
('Double Stag Counter Balance','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/05/06-DSC07366-2.jpg'),
('Shin to Foot','L-Base','Easy','2 Person','https://www.acropedia.org/wp-content/uploads/2016/07/Shin-to-Foot.jpg'),
('Double-Base Hand to Hand','L-Base','Expert','3 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2015/09/double-hand-to-hand.jpg?fit=1536%2C2048&ssl=1'),
('Foot Sirsasana','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/12/Foot-Sirasana.jpg'),
('High Spoon','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2016/05/High-Spoon.jpg'),
('Pike Pyramid','L-Base','Intermediate','3 Person','https://www.acropedia.org/wp-content/uploads/2016/07/DSC_3541.jpg'),
('Hand-to-Hand','L-Base','Really Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2015/09/h2h-josh-wari.jpg'),
('Double Knee Drop','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/05/30-DSC07589-2-1.jpg'),
('Foot-To-Foot Lord of the Dance Pose','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Foot-to-foot-Lord-of-the-dance-pose-.jpg'),
('Leaf Twist','L-Base','Intermediate','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Leaf-Twist1.jpg?fit=600%2C400&ssl=1'),
('Bluejay','L-Base','Hard','4 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Bluejay.jpg'),
('Maple','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2017/07/maple-lesh-amir.jpg'),
('Mono-Limb Reverse Star','L-Base','Really Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2015/09/DSC_6395.jpg'),
('Headfirst Grasshopper','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2017/04/DSC_3603-2.jpg'),
('Low Foot-to-Hand','L-Base','Hard','2 Person','https://i2.wp.com/www.acropedia.org/wp-content/uploads/2013/07/foot-to-hand.jpg?fit=600%2C400&ssl=1'),
('Scare Crow','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2014/01/Scare-Crow2.jpg?fit=600%2C400&ssl=1'),
('Boredstand','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2016/09/Boredstand.jpg'),
('Table Top','L-Base','Hard','2 Person','https://i2.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Reverse-Table-Top.jpg?fit=600%2C400&ssl=1'),
('Hammock','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Hammock.jpg?fit=600%2C400&ssl=1'),
('Folded Leaf','L-Base','Easy','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Folded-Leaf.jpg?fit=600%2C400&ssl=1'),
('Heart to Hands','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2014/01/Heart-to-Hands.jpg?fit=600%2C400&ssl=1'),
('Spoon','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Spoon.jpg?fit=600%2C400&ssl=1'),
('Hangle Dangle','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/07/hangle-dangle.jpg'),
('Pasarita Twist','L-Base','Hard','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Pasarita-Twist.jpg?fit=600%2C400&ssl=1'),
('Floating Camel','L-Base','Really Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/07/DSC_8202.jpg'),
('Super Yogi','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/07/super-yogi.jpg?fit=600%2C400&ssl=1'),
('Navasana','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2013/07/Navasana.jpg'),
('Super Natural','L-Base','Easy','2 Person','https://i2.wp.com/www.acropedia.org/wp-content/uploads/2014/01/Super-Natural.jpg?fit=600%2C400&ssl=1'),
('Super Yogi Twist','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2014/01/Super-Yogi-Twist.jpg?fit=600%2C400&ssl=1'),
('Bat','L-Base','Easy','2 Person','https://i2.wp.com/www.acropedia.org/wp-content/uploads/2014/02/CranioSacral.jpg?fit=600%2C400&ssl=1'),
('Reverse Bat','L-Base','Intermediate','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2013/08/Walnut1.jpg?fit=600%2C400&ssl=1'),
('Tuck Sit','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Tuck-Sit-Tag.jpg?fit=600%2C400&ssl=1'),
('Heart to Shin','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2014/01/Heart-to-Shin.jpg?fit=600%2C400&ssl=1'),
('Reverse Couch','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Reverse-Vasi-Tag.jpg?fit=600%2C400&ssl=1'),
('Reverse Tuck Sit','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Reverse-Tuck-Sit-Tag.jpg?fit=600%2C400&ssl=1'),
('Bound Twist','L-Base','Intermediate','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2014/01/Bound-Twist.jpg?fit=600%2C400&ssl=1'),
('Reverse Throne','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Reverse-throne.jpg?fit=600%2C400&ssl=1'),
('Whaka Stretch','L-Base','Easy','2 Person','https://i2.wp.com/www.acropedia.org/wp-content/uploads/2014/02/Whaka-Stretch.jpg?fit=600%2C400&ssl=1'),
('Throne','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/06/Throne.jpg?fit=600%2C371&ssl=1'),
('Side Star','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/06/DSC_0720.jpg'),
('Floating Pashi','L-Base','Intermediate','2 Person','https://i2.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Floating-Pashi-TAG.jpg?fit=600%2C400&ssl=1'),
('Mermaid','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/06/Mermaid-Wari.jpg?fit=600%2C400&ssl=1'),
('Little Mermaid','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/06/Little-Mermaid.jpg'),
('Croc','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/06/DSC_4705-color_1432078188_703.jpg'),
('Bow','L-Base','Easy','2 Person','https://www.acropedia.org/wp-content/uploads/2014/02/Bow.jpg'),
('Reverse Back Plank','L-Base','Intermediate','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Reverse-Back-Plank.jpg?fit=600%2C400&ssl=1'),
('Reverse Prayer','L-Base','Easy','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2014/01/Reverse-Prayer2.jpg?fit=600%2C400&ssl=1'),
('Whale','L-Base','Easy','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Whale.jpg?fit=600%2C400&ssl=1'),
('Low hand-to-hand','L-Base','Really Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/06/DSC_6834.jpg'),
('Vishnu’s Couch','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/06/vasi-acro-2696.jpg?fit=600%2C400&ssl=1'),
('Straddle Bat','L-Base','Easy','2 Person','https://www.acropedia.org/wp-content/uploads/2013/02/straddle-bat.jpg'),
('Reverse Shoulder Stand','L-Base','Intermediate','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/06/reverse-shoulder-stand.jpg?fit=533%2C400&ssl=1'),
('Reverse Tittibhasana','L-Base','Hard','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/07/Reverse-Titti.jpg?fit=600%2C400&ssl=1'),
('Nataraj','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/06/nataraj.jpg?fit=600%2C400&ssl=1'),
('Foot-to-Foot','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/06/Kadri-f2h.jpg'),
('Tittibhasana','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/07/DSC_2220-color_1429234022_201.jpg'),
('Front Plank','L-Base','Easy','2 Person','https://i1.wp.com/www.acropedia.org/wp-content/uploads/2013/06/bird-acro-1114.jpg?fit=600%2C400&ssl=1'),
('Reverse Star','L-Base','Hard','2 Person','https://www.acropedia.org/wp-content/uploads/2013/02/reverse-star.jpg'),
('Back Bird','L-Base','Easy','2 Person','https://www.acropedia.org/wp-content/uploads/2013/06/DSC_9774.jpg'),
('Couch','L-Base','Intermediate','2 Person','https://i0.wp.com/www.acropedia.org/wp-content/uploads/2013/06/Vishnus-couch-4248.jpg?fit=600%2C400&ssl=1'),
('Free Shoulder Stand','L-Base','Intermediate','2 Person','https://www.acropedia.org/wp-content/uploads/2013/02/DSC_7059.jpg');